version: '3'

networks:
  identity-service-network: # Define la red personalizada
    driver: bridge # Puedes cambiar el controlador de red según tus necesidades

services:
  msgf-identity-service:
    container_name: msgf-identity-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - identity-service-db
    environment:
      # Configuración para tu aplicación Spring Boot
      SPRING_DATASOURCE_URL: jdbc:postgresql://identity-service-db:5432/identity-service-db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    networks:
      - identity-service-network # Asigna el servicio a la red personalizada

  identity-service-db:
    container_name: identity-service-db
    image: postgres:latest
    environment:
      POSTGRES_DB: identity-service-db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - identity-service-network # Asigna el servicio a la red personalizada

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - identity-service-db
    command: ["start-dev"]
    networks:
      - identity-service-network # Asigna el servicio a la red personalizada
